// Generated by scripts/build-shell.mjs from apps/shell/src/theme.ts. Do not edit.
(() => {
  const ID = 'colai-theme';
  const put = () => {
    if (!document.head || document.getElementById(ID)) return;
    const style = document.createElement('style');
    style.id = ID;
    style.textContent = ":root,\n:root[data-theme=\"dark\"],\n:root[data-theme=\"light\"],\n:root[data-theme=\"custom\"],\n:root[data-theme=\"custom-light\"] {\n  --bg: #070B14;\n  --bg-accent: #111828;\n  --bg-elevated: #111828;\n  --bg-hover: #1A2338;\n  --bg-muted: #0B101D;\n  --bg-content: #0B101D;\n  --card: #0B101D;\n  --card-foreground: #F2F5F3;\n  --card-highlight: #111828;\n  --popover: #111828;\n  --popover-foreground: #F2F5F3;\n  --panel: #0B101D;\n  --panel-strong: #111828;\n  --panel-hover: #1A2338;\n  --chrome: #0B101D;\n  --chrome-strong: #070B14;\n  --text: #F2F5F3;\n  --text-strong: #FFFFFF;\n  --chat-text: #F2F5F3;\n  --muted: #111828;\n  --muted-strong: #1A2338;\n  --muted-foreground: #8E9AAF;\n  --border: rgba(255,255,255,.10);\n  --border-strong: rgba(255,255,255,.18);\n  --border-hover: rgba(255,255,255,.26);\n  --input: #111828;\n  --ring: #00C389;\n  --accent: #00C389;\n  --accent-hover: #26D49E;\n  --accent-muted: rgba(0,195,137,.16);\n  --accent-subtle: rgba(0,195,137,.08);\n  --accent-foreground: #070B14;\n  --accent-glow: rgba(0,195,137,.35);\n  --primary: #00C389;\n  --primary-foreground: #070B14;\n  --secondary: #1A2338;\n  --secondary-foreground: #F2F5F3;\n  --accent-2: #2E6FE8;\n  --accent-2-muted: rgba(46,111,232,.16);\n  --accent-2-subtle: rgba(46,111,232,.08);\n  --destructive: #D93B41;\n  --destructive-foreground: #FFFFFF;\n  --danger: #D93B41;\n  --danger-muted: rgba(217,59,65,.16);\n  --danger-subtle: rgba(217,59,65,.08);\n  --focus: #00C389;\n  --focus-ring: rgba(0,195,137,.55);\n  --focus-glow: rgba(0,195,137,.25);\n  --font-body: 'Instrument Sans', system-ui, sans-serif;\n  --font-display: 'Space Grotesk', system-ui, sans-serif;\n  --mono: 'JetBrains Mono', ui-monospace, monospace;\n  --grid-line: rgba(255,255,255,.06);\n}\n";
    document.head.appendChild(style);
  };
  put();
  document.addEventListener('DOMContentLoaded', put);
  // The interface writes its own theme tag when settings load; ours is a different id
  // and is appended after, so it survives that and wins on order.
  new MutationObserver(put).observe(document.documentElement, { childList: true, subtree: true });
})();
